version: '3.8'
services:
  app:
    build: .
    container_name: pdf-classifier-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:root@db/pdf_classifier
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: pdf-classifier-db
    restart: always
    environment:
      MYSQL_DATABASE: pdf_classifier
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
